import shoeImg from "./assets/shoe.jpg"
import shoe1 from "./assets/shoe1.jpg"
import shoe2 from "./assets/shoe2.jpg"
import shoe3 from "./assets/shoe3.jpg"
import shoe4 from "./assets/shoe4.jpg"
import shoe5 from "./assets/shoe5.jpg"
import shoe6 from "./assets/shoe6.jpg"
import shoe7 from "./assets/shoe7.jpg"
import shoe8 from "./assets/shoe8.jpg"
import shoe9 from "./assets/shoe9.jpg"



export const products = [
  {
    name: "Air Runner",
    price: 89.99,
    image: shoe1,
    description: "Lightweight everyday wear",
    brand: "Nike",
    color: "black",
    category: "Running",
    gender: "Men",
    onSale: true,
  },
  {
    name: "Urban Glide",
    price: 74.5,
    image: shoe2,
    description: "Stylish and durable urban trainer",
    brand: "Adidas",
    color: "white",
    category: "Everyday",
    gender: "Women",
    onSale: false,
  },
  {
    name: "Classic Comfort",
    price: 59.95,
    image: shoe3,
    description: "Soft cushioning for daily use",
    brand: "Puma",
    color: "blue",
    category: "Everyday",
    gender: "Men",
    onSale: true,
  },
  {
    name: "Trail Master",
    price: 99.0,
    image: shoe4,
    description: "Reliable grip for off-road adventures",
    brand: "Nike",
    color: "green",
    category: "Running",
    gender: "Men",
    onSale: false,
  },
  {
    name: "Sprint Edge",
    price: 120.0,
    image: shoe5,
    description: "Designed for competitive performance",
    brand: "Adidas",
    color: "red",
    category: "Running",
    gender: "Women",
    onSale: true,
  },
  {
    name: "Eco Walk",
    price: 65.25,
    image: shoe6,
    description: "Sustainable and eco-friendly shoes",
    brand: "Vans",
    color: "white",
    category: "Everyday",
    gender: "Women",
    onSale: false,
  },
  {
    name: "Daily Step",
    price: 49.99,
    image: shoe7,
    description: "Affordable everyday comfort",
    brand: "Puma",
    color: "black",
    category: "Everyday",
    gender: "Boys/Girls",
    onSale: true,
  },
  {
    name: "Court Pulse",
    price: 82.45,
    image: shoe8,
    description: "Built for quick movements on court",
    brand: "Converse",
    color: "red",
    category: "Skate",
    gender: "Men",
    onSale: false,
  },
  {
    name: "Flex Motion",
    price: 110.0,
    image: shoe1,
    description: "Flexible design with superior support",
    brand: "Nike",
    color: "blue",
    category: "Cleats",
    gender: "Women",
    onSale: true,
  },
  {
    name: "Cloud Tread",
    price: 95.0,
    image: shoeImg,
    description: "Soft steps for long walks",
    brand: "Vans",
    color: "green",
    category: "Everyday",
    gender: "Men",
    onSale: false,
  },
  {
    name: "Velocity Pro",
    price: 130.0,
    image: shoeImg,
    description: "High-speed running shoe",
    brand: "Adidas",
    color: "black",
    category: "Running",
    gender: "Men",
    onSale: true,
  },
  {
    name: "Ridge Trek",
    price: 105.0,
    image: shoe3,
    description: "Outdoor trekking companion",
    brand: "Nike",
    color: "green",
    category: "Running",
    gender: "Women",
    onSale: false,
  },
  {
    name: "Slide Skater",
    price: 70.0,
    image: shoe4,
    description: "Board-gripping skate shoes",
    brand: "Converse",
    color: "blue",
    category: "Skate",
    gender: "Boys/Girls",
    onSale: true,
  },
  {
    name: "Metro Sprint",
    price: 85.0,
    image: shoe7,
    description: "Perfect for city runners",
    brand: "Puma",
    color: "white",
    category: "Running",
    gender: "Men",
    onSale: false,
  },
  {
    name: "Formal Luxe",
    price: 140.0,
    image: shoe9,
    description: "Premium formal wear",
    brand: "Nike",
    color: "black",
    category: "Formal",
    gender: "Men",
    onSale: false,
  },
  {
    name: "Active Dash",
    price: 78.0,
    image: shoe2,
    description: "Versatile activity shoe",
    brand: "Vans",
    color: "red",
    category: "Everyday",
    gender: "Women",
    onSale: true,
  },
  {
    name: "Power Kick",
    price: 115.0,
    image: shoe2,
    description: "Engineered for cleat traction",
    brand: "Adidas",
    color: "blue",
    category: "Cleats",
    gender: "Men",
    onSale: false,
  },
  {
    name: "Skater Rush",
    price: 69.5,
    image: shoe1,
    description: "Durable grip for skaters",
    brand: "Converse",
    color: "black",
    category: "Skate",
    gender: "Women",
    onSale: true,
  },
  {
    name: "Quick Shift",
    price: 90.0,
    image: shoe5,
    description: "Shift and sprint with ease",
    brand: "Puma",
    color: "green",
    category: "Running",
    gender: "Men",
    onSale: false,
  },
  {
    name: "Walk Ease",
    price: 55.0,
    image: shoe6,
    description: "Daily comfort for all ages",
    brand: "Nike",
    color: "white",
    category: "Everyday",
    gender: "Boys/Girls",
    onSale: true,
  },
];
